fix(workflows): upgrade `auto-update` workflow to use `add-and-commit@v9.1.4`
The "Commit changes" step would fail with the following error from `git`:

```
Staging files in commit path...
error: unknown switch `t'
usage: git add [<options>] [--] <pathspec>...
```

This is evidently the result of some poor input quoting in `add-and-commit`
and the (strange) appearance of cases with spaces in the `docket_number`
field of some Oyez responses. The latter would produce the following files,
which, when ingested by the former would cause the error:

```
oyez/cases/2024.23-217-t01.json
oyez/cases/2024.23-217.json
oyez/cases/2024.23-365 -t01.json
oyez/cases/2024.23-365 .json
oyez/cases/2024.23-365-t01.json
oyez/cases/2024.23-365.json
oyez/cases/2024.23-477-t01.json
oyez/cases/2024.23-477.json
oyez/cases/2024.23-583 -t01.json
oyez/cases/2024.23-583 .json
oyez/cases/2024.23-583-t01.json
oyez/cases/2024.23-583.json
```

Upgrading `add-and-commit` from `v2.1.0` to the latest version, `v9.1.4`,
is a sufficient fix. This leap in versions requires several adjustments:

- A named `ref` is added to `checkout` step (as well as an upgrade from `v1`)
- `path` and `pattern` are replaced by `add` (see `v4.0.0`)